| schemaname | tablename               | policyname                           | permissive | roles           | cmd    | qual                                                                                                                           | with_check                                                                                                                     |
| ---------- | ----------------------- | ------------------------------------ | ---------- | --------------- | ------ | ------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------ |
| public     | container_scans         | container_scans_delete_own           | PERMISSIVE | {authenticated} | DELETE | (auth.uid() = user_id)                                                                                                         | null                                                                                                                           |
| public     | container_scans         | container_scans_insert_own           | PERMISSIVE | {authenticated} | INSERT | null                                                                                                                           | (auth.uid() = user_id)                                                                                                         |
| public     | container_scans         | container_scans_select_admin         | PERMISSIVE | {authenticated} | SELECT | (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 1))))                             | null                                                                                                                           |
| public     | container_scans         | container_scans_select_own           | PERMISSIVE | {authenticated} | SELECT | (auth.uid() = user_id)                                                                                                         | null                                                                                                                           |
| public     | field_samples           | Users insert their own samples       | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | ((auth.uid() = user_id) OR (user_id IS NULL))                                                                                  |
| public     | field_samples           | Users read their own samples         | PERMISSIVE | {public}        | SELECT | ((auth.uid() = user_id) OR (user_id IS NULL))                                                                                  | null                                                                                                                           |
| public     | field_samples           | field_samples_select_admin           | PERMISSIVE | {authenticated} | SELECT | (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 1))))                             | null                                                                                                                           |
| public     | field_samples           | field_samples_select_own             | PERMISSIVE | {authenticated} | SELECT | (auth.uid() = user_id)                                                                                                         | null                                                                                                                           |
| public     | forum_categories        | forum_categories_select              | PERMISSIVE | {public}        | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | forum_notifications     | forum_notifications_select_own       | PERMISSIVE | {public}        | SELECT | (auth.uid() = recipient_user_id)                                                                                               | null                                                                                                                           |
| public     | forum_notifications     | forum_notifications_update_own       | PERMISSIVE | {public}        | UPDATE | (auth.uid() = recipient_user_id)                                                                                               | (auth.uid() = recipient_user_id)                                                                                               |
| public     | forum_post_likes        | forum_post_likes_delete_own          | PERMISSIVE | {public}        | DELETE | (auth.uid() = user_id)                                                                                                         | null                                                                                                                           |
| public     | forum_post_likes        | forum_post_likes_insert              | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | (auth.uid() = user_id)                                                                                                         |
| public     | forum_post_likes        | forum_post_likes_select              | PERMISSIVE | {public}        | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | forum_posts             | forum_posts_insert                   | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | (auth.uid() = user_id)                                                                                                         |
| public     | forum_posts             | forum_posts_select                   | PERMISSIVE | {public}        | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | forum_posts             | forum_posts_update_own               | PERMISSIVE | {public}        | UPDATE | (auth.uid() = user_id)                                                                                                         | (auth.uid() = user_id)                                                                                                         |
| public     | forum_thread_categories | forum_thread_categories_delete_owner | PERMISSIVE | {public}        | DELETE | (EXISTS ( SELECT 1
   FROM forum_threads t
  WHERE ((t.id = forum_thread_categories.thread_id) AND (t.user_id = auth.uid())))) | null                                                                                                                           |
| public     | forum_thread_categories | forum_thread_categories_insert_owner | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | (EXISTS ( SELECT 1
   FROM forum_threads t
  WHERE ((t.id = forum_thread_categories.thread_id) AND (t.user_id = auth.uid())))) |
| public     | forum_thread_categories | forum_thread_categories_select       | PERMISSIVE | {public}        | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | forum_thread_likes      | forum_thread_likes_delete_own        | PERMISSIVE | {public}        | DELETE | (auth.uid() = user_id)                                                                                                         | null                                                                                                                           |
| public     | forum_thread_likes      | forum_thread_likes_insert            | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | (auth.uid() = user_id)                                                                                                         |
| public     | forum_thread_likes      | forum_thread_likes_select            | PERMISSIVE | {public}        | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | forum_threads           | forum_threads_delete_own             | PERMISSIVE | {public}        | DELETE | (auth.uid() = user_id)                                                                                                         | null                                                                                                                           |
| public     | forum_threads           | forum_threads_insert                 | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | (auth.uid() = user_id)                                                                                                         |
| public     | forum_threads           | forum_threads_select                 | PERMISSIVE | {public}        | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | forum_threads           | forum_threads_update_own             | PERMISSIVE | {public}        | UPDATE | (auth.uid() = user_id)                                                                                                         | (auth.uid() = user_id)                                                                                                         |
| public     | profiles                | profiles_admin_select_all            | PERMISSIVE | {authenticated} | SELECT | is_admin_user()                                                                                                                | null                                                                                                                           |
| public     | profiles                | profiles_admin_update_all            | PERMISSIVE | {authenticated} | UPDATE | is_admin_user()                                                                                                                | is_admin_user()                                                                                                                |
| public     | profiles                | profiles_insert_own                  | PERMISSIVE | {authenticated} | INSERT | null                                                                                                                           | (auth.uid() = id)                                                                                                              |
| public     | profiles                | profiles_select_authenticated        | PERMISSIVE | {authenticated} | SELECT | true                                                                                                                           | null                                                                                                                           |
| public     | profiles                | profiles_select_own                  | PERMISSIVE | {public}        | SELECT | (auth.uid() = id)                                                                                                              | null                                                                                                                           |
| public     | profiles                | profiles_update_own                  | PERMISSIVE | {authenticated} | UPDATE | (auth.uid() = id)                                                                                                              | (auth.uid() = id)                                                                                                              |
| storage    | objects                 | Users can delete their avatar        | PERMISSIVE | {public}        | DELETE | ((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text))                                                      | null                                                                                                                           |
| storage    | objects                 | Users can update their avatar        | PERMISSIVE | {public}        | UPDATE | ((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text))                                                      | ((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text))                                                      |
| storage    | objects                 | Users can upload their avatar        | PERMISSIVE | {public}        | INSERT | null                                                                                                                           | ((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text))                                                      |
| storage    | objects                 | avatars_delete_own                   | PERMISSIVE | {authenticated} | DELETE | ((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                                       | null                                                                                                                           |
| storage    | objects                 | avatars_update_own                   | PERMISSIVE | {authenticated} | UPDATE | ((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                                       | ((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                                       |
| storage    | objects                 | avatars_upload_own                   | PERMISSIVE | {authenticated} | INSERT | null                                                                                                                           | ((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                                       |
| storage    | objects                 | container_scans_delete_own           | PERMISSIVE | {authenticated} | DELETE | ((bucket_id = 'container-scans'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                               | null                                                                                                                           |
| storage    | objects                 | container_scans_update_own           | PERMISSIVE | {authenticated} | UPDATE | ((bucket_id = 'container-scans'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                               | ((bucket_id = 'container-scans'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                               |
| storage    | objects                 | container_scans_upload_own           | PERMISSIVE | {authenticated} | INSERT | null                                                                                                                           | ((bucket_id = 'container-scans'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))                               |