import { useNavigate } from 'react-router-dom';

export default function TermsOfServicePage() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-slate-50 px-4 py-16">
      <div className="mx-auto max-w-2xl">
        {/* Back button */}
        <button
          onClick={() => navigate('/')}
          className="mb-8 flex items-center gap-2 text-sm text-slate-500 transition-colors hover:text-sky-600"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
          Back to site
        </button>

        {/* Header */}
        <div className="mb-10 text-center">
          <p className="text-xs uppercase tracking-[0.4em] text-sky-600">AquaScope</p>
          <h1 className="mt-2 text-3xl font-bold text-slate-900">Terms of Service</h1>
          <p className="mt-2 text-sm text-slate-500">Effective date: March 2026</p>
        </div>

        <div className="space-y-8 rounded-2xl border border-slate-200 bg-white px-8 py-10 text-sm leading-relaxed text-slate-700 shadow-sm">

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">1. Nature of the Service</h2>
            <p>
              AquaScope is a student-built academic platform that uses machine learning models to
              assess water quality risk and potability based on physicochemical parameters. It is
              intended for educational and demonstrative purposes only — <strong>not for
              professional, medical, or regulatory use</strong>.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">2. Acceptance of Terms</h2>
            <p>
              By registering an account or using any feature of AquaScope, you agree to these Terms.
              If you do not agree, please do not use the platform.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">3. Use of Predictions</h2>
            <p>
              Predictions and risk assessments generated by AquaScope are produced by machine
              learning models and may not be accurate. Do <strong>not</strong> use outputs from this
              platform as the sole basis for decisions about water safety, health, or public policy.
              Always consult certified water quality professionals or regulatory bodies.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">4. User Responsibilities</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>You must provide accurate information when registering.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must not misuse the platform, upload malicious content, or attempt to compromise the system.</li>
              <li>You must not use the platform for commercial purposes.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">5. Disclaimers & Limitation of Liability</h2>
            <p>
              AquaScope is provided as-is for academic evaluation. The developers — Kim Jensen
              Yebes, Jay Tabigue, Ryan Russel Antoniano, and Alsamuel Crueta — make no warranties
              of any kind regarding the accuracy, reliability, or fitness of the service for any
              particular purpose. To the fullest extent permitted, the developers are not liable for
              any damages arising from use of this platform.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">6. Service Availability</h2>
            <p>
              As an academic project, AquaScope may be taken offline, reset, or modified at any
              time without prior notice. We do not guarantee continuous availability.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">7. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms at any time. Continued use of the platform
              after changes are posted constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-semibold text-slate-900">8. Contact</h2>
            <p>
              For questions about these Terms, contact the development team through your institution's
              designated channels.
            </p>
          </section>
        </div>

        <p className="mt-8 text-center text-xs text-slate-400">
          &copy; 2026 AquaScope — Academic Project &middot;{" "}
          <a href="/privacy" className="text-sky-500 hover:underline">Privacy Policy</a>
        </p>
      </div>
    </div>
  );
}
